---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if services are started and enabled
    systemd:
      enabled: true
      name: "grafana-server.service"
      masked: false
      state: started

  - name: (check) Test if services ports are open and reachable
    wait_for:
      port: "3000"

  - name: (check) Test if Grafana web interface is OK
    uri:
      status_code: 200
      url: "http://localhost:3000"
